apiVersion: v1
kind: Pod
metadata:
  name: kviewer-pod
  labels:
    version: alphav1
    app: kviewer
spec:
  containers:
  - name: kviewer-svr
    image: robertireton/kviewer
    ports:
    - containerPort: 8088
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
